api/code-samples/javascript/eth/others/createAccessList.js
api/code-samples/javascript/klay/gas/upperBoundGasPrice.js
api/paths/eth/others/createAccessList.yaml
api/paths/klay/gas/upperBoundGasPrice.yaml
sdk/client/javascript/openapi-test/test/eth/others/EthCreateAccessListApi.test.js
sdk/client/javascript/openapi-test/test/klay/configuration/KlayRewardbaseApi.test.js
sdk/client/javascript/openapi-test/test/klay/gas/KlayUpperBoundGasPriceApi.test.js

Fix: js sdk for klay and eth

---

documentation/index.yaml
documentation/site/README.md

- klaytn-openapi.yaml contents was deleted in  documentation/site/README.md
- changed the tag group names

Documentation small fix

---

web3rpc/rpc-specs/generate-namespace.sh
web3rpc/rpc-specs/paths/all-except-eth/index.yaml
web3rpc/rpc-specs/paths/eth/index.yaml
web3rpc/rpc-specs/paths/klay/index.yaml
web3rpc/rpc-specs/redocly.yaml
web3rpc/sdk/client/javascript/javascript-config.yaml
web3rpc/sdk/client/javascript/javascript-generate.sh

- make web3rpc javascript library one module
- removed repeated APIs
- eth namespace
- personal.sign/personal.sendTransaction/personal.signTransaction
- governance/getStakingInfo, governance/nodeAddress
- we can use the ethersjs's eth namespace functions instead of the deleted eth namespace APIs
- we can use the same APIs in klay namespace instead of the deleted personal/governance APIs

make web3rpc-javascript one module with classes for each namespaces

---

web3rpc/codegen/src/main/kotlin/web3rpc/client/KlaytnJavaClientCodegen.kt
web3rpc/rpc-specs/paths/klay/account/getAccount.yaml
web3rpc/sdk/client/java/openapi-test/src/test/java/opensdk/sdk/apis/klay/account/KlayGetAccountApiTest.java
web3rpc/sdk/client/java/openapi-test/src/test/java/opensdk/sdk/apis/klay/transaction/KlaySendTransactionAsFeePayerTest.java
web3rpc/sdk/client/java/openapi-test/src/test/java/opensdk/sdk/apis/klay/transaction/KlaySignTransactionAsFeePayerTest.java
web3rpc/sdk/client/java/template/KlayGetAccountAccountKey.java.mustache

I fixed the deserialization issue in the case of an account belonging to the role-based type. In my commit, I did the following:
- Updated documentation for the klay_getAccount RPC section.
- Created a mustache file to override the object within the response returned by klay_getAccount RPC.
In case of returning a null key when the account is a multisig account, it appears that the key field in the response is an empty object.

update response of rpc klay_getAccount

---

ethers-ext/package-lock.json
ethers-ext/package.json
ethers-ext/test/core/klaytn_tx.spec.ts
ethers-ext/test/ethers/mock_provider.ts
ethers-ext/test/ethers/signer.spec.ts

- Add unit tests for KlaytnTxFactory and KlaytnWallet
- Some tests will be added later
- Now `npm run test` passes

ethers: Add unit tests

---

ethers-ext/src/ethers/signer.ts

-  Add logic to make ethers' JsonRpcProvider and Klaytn's JsonRpcProvider compatible
This can be done in two ways:
`
const provider = new ethers.providers.JsonRpcProvider(“https://public-en-baobab.klaytn.net”);
`
or
`
const provider = new JsonRpcProvider(“https://public-en-baobab.klaytn.net”);
`
- Adjust default gas estimate multi-factor

Signer bug fix

---

ethers-ext/.eslintrc.js
ethers-ext/src/ethers/signer.ts

This dynamic extension mechanism does not work as of now.
I propose to remove the feature until we know a clean solution or choose not to implement a dynamic extension.
Below code fails because `ew.populateTransaction` calls the vanilla ethers method.
```js
const ethers = require("ethers");
const { Wallet, JsonRpcProvider } = require("@klaytn/ethers-ext");
async function main() {
var provider = new JsonRpcProvider("https://public-en-baobab.klaytn.net");
var key = "0e4ca6d38096ad99324de0dde108587e5d7c600165ae4cd6c2462c597458c2b8";
var addr = '0xa2a8854b1802d8cd5de631e690817c253d6a9153';
var tx = { type: 9, from: addr, to: addr, feePayer: addr, value: 0 };
var kw = new Wallet(key, provider, true);
var kt = await kw.populateTransaction(tx);
console.log(kt);
var ew = new ethers.Wallet(key, …
```

ethers: Remove Wallet dynamicUpdateWalletAPI

---

ethers-ext/src/ethers/signer.ts

- Restoring chainId field that disappears as it is changed to RLP format
- When signing with feePayer, if the feePayer field is null, the address of the current wallet is set as the default value.

Fix signTransactionAsFeePayer

---

ethers-ext/src/core/klaytn_tx.ts
ethers-ext/src/ethers/signer.ts
ethers-ext/test/core/klaytn_tx.spec.ts

When calling some RPCs (eth_estimateGas, eth_call), the transaction arguments must be properly hexlified.
(https://github.com/klaytn/klaytn/blob/dev/api/tx_args.go#L536)
Zero numeric values must be encoded to "0x0" and
Empty bytes and address values must be "0x".

ethers: Fix encodeTxForRPC to separately handle 0x and 0x0

---

ethers-ext/package.json
web3j-ext/web3j-ext/build.gradle
web3py-ext/setup.py
web3rpc/sdk/client/java/java-config.yaml
web3rpc/sdk/client/javascript/javascript-config.yaml

- web3rpc-javascript (as is 0.9.0 --> to be 0.9.4)
- to sync with other packages
- web3rpc-java (as is 0.9.3 --> to be 0.9.4)
- ethers-ext (as is 0.9.3-beta --> to be 0.9.4-beta)
- It is currently using the web3rpc-javascript-v0.9.0 and will has no any changes (will be changed in next release)
- web3j-ext (as is 0.9.3 --> to be 0.9.4)
- It is currently using the web3rpc-java-v0.9.0 and will be updated to use v0.9.3 (can’t use v0.9.4 because deploy delay)
- web3py-ext (as is 0.9.3-beta --> to be 0.9.4-beta)

version up to v0.9.4

---

ethers-ext/package-lock.json
ethers-ext/package.json
ethers-ext/src/ethers/keystore/decrypt.ts
ethers-ext/src/ethers/keystore/index.ts
ethers-ext/src/ethers/keystore/type.ts
ethers-ext/src/ethers/signer.ts
ethers-ext/test/ethers/decrypt_encrypt.spec.ts

Additional decrypt function into ether-ext
Keystore v4 format support example
- Parse multisig or rolebase key that includes 3 keys into multiple json for each key
- Decrypt the keys
- Took the code from Ethers to bypass the address comparison part.
- Return Wallet instance

feat: add decrypt function into ether ext

---

ethers-ext/example/signRecover/1_tx_signRecover_legacy.js
ethers-ext/example/signRecover/2_tx_signRecover_pubkey.js
ethers-ext/example/signRecover/3_tx_signRecover_multisig.js
ethers-ext/example/signRecover/4_tx_signRecover_rolebased.js
ethers-ext/example/signRecover/5_msg_signRecover_legacy.js
ethers-ext/example/signRecover/6_msg_signRecover_pubkey.js
ethers-ext/example/signRecover/7_msg_signRecover_multisig.js
ethers-ext/example/signRecover/8_msg_signRecover_rolebased.js

- signRecover for transaction (legacy, pubkey, multisig, rolebased) 
- signRecover for message (legacy, pubkey, multisig, rolebased)

Ethers.js EXT examples for signRecover

---

web3js-ext/example/create.js
web3js-ext/example/privateKeyToAccount.js
web3js-ext/example/recoverTransaction.js
web3js-ext/example/wallet.js
web3js-ext/src/web3/account.ts
web3js-ext/src/web3/web3.ts

Override the web3.eth.accounts functions to bind with updated functions to support Klaytn features.
- create
- privateKeyToAccount
- signTransaction
- recoverTransaction
- decrypt (To be updated for supporting KeyStore V4)

Overriding web3.eth.accounts

---

ethers-ext/example/accountKey/AccountKeyPublic.js
ethers-ext/example/accountKey/AccountKeyRoleBased.js
ethers-ext/example/accountKey/AccountKeyWeightedMultiSig.js
ethers-ext/example/transactions/Basic_08_TxTypeValueTransfer.js
ethers-ext/example/transactions/Basic_10_TxTypeValueTransferMemo.js
ethers-ext/example/transactions/Basic_20_TxTypeAccountUpdate.js
ethers-ext/example/transactions/Basic_28_TxTypeSmartContractDeploy.js
ethers-ext/example/transactions/Basic_30_TxTypeSmartContractExecution.js
ethers-ext/example/transactions/Basic_38_TxTypeCancel.js
ethers-ext/example/transactions/FeeDel_09_TxTypeFeeDelegatedValueTransfer.js
ethers-ext/example/transactions/FeeDel_09_TxTypeFeeDelegatedValueTransfer2.js
ethers-ext/example/transactions/FeeDel_11_TxTypeFeeDelegatedValueTransferMemo.js
ethers-ext/example/transactions/FeeDel_21_TxTypeFeeDelegatedAccountUpdate.js
ethers-ext/example/transactions/FeeDel_29_TxTypeFeeDelegatedSmartContractDeploy.js
ethers-ext/example/transactions/FeeDel_31_TxTypeFeeDelegatedSmartContractExecution.js
ethers-ext/example/transactions/FeeDel_39_TxTypeFeeDelegatedCancel.js
ethers-ext/example/transactions/PartialFeeDel_0a_TxTypeFeeDelegatedValueTransferWithRatio.js
ethers-ext/example/transactions/PartialFeeDel_12_TxTypeFeeDelegatedValueTransferMemoWithRatio.js
ethers-ext/example/transactions/PartialFeeDel_22_TxTypeFeeDelegatedAccountUpdateWithRatio.js
ethers-ext/example/transactions/PartialFeeDel_2a_TxTypeFeeDelegatedSmartContractDeployWithRatio.js
ethers-ext/example/transactions/PartialFeeDel_32_TxTypeFeeDelegatedSmartContractExecutionWithRatio.js
ethers-ext/example/transactions/PartialFeeDel_3a_TxTypeFeeDelegatedCancelWithRatio.js

- js-ext-core is deployed, and  ethers-ext includes js-ext-core/util 
- Some module path for TyType, parseKlay, etc. in example is updated.

Update ethers examples to not import js-ext-core

---

ethers-ext/package.json
js-ext-core/package.json
web3j-ext/web3j-ext/build.gradle
web3js-ext/package.json
web3py-ext/setup.py
web3rpc/rpc-specs/package.json
web3rpc/sdk/client/java/java-config.yaml
web3rpc/sdk/client/javascript/javascript-config.yaml

Changes
- the first release for the **web3js-ext**
- ethers-ext and web3js-ext will import js-core-ext module in common library
- #534 
- #549 
- example update and minor bugfix
- #547
- #548 
- #550
- #551

version up to 0.9.8-beta

---

web3js-ext/package.json

Fix errors in the exported path of package.json.

web3js-ext: Patch the exported path in package.json

---

web3js-ext/package.json

Version upgrade to 0.9.9-beta due to hotfix https://github.com/klaytn/web3klaytn/pull/558.

web3js-ext : version up 0.9.9-beta

---

js-ext-core/package.json
js-ext-core/src/util/ec.ts
js-ext-core/test/util.spec.ts

- The util function `getPublicKeyFromPrivate` will be useful in composing AccountUpdate transactions.
- Private Key -> Public Key conversion is frustrating in both ethers.js and web3.js
**As-is**
https://github.com/klaytn/web3klaytn/blob/4e6c944cf31f244775ee59fc772ba17680533c19/ethers-ext/example/accountKey/AccountKeyPublic.js#L17
https://github.com/klaytn/web3klaytn/blob/4e6c944cf31f244775ee59fc772ba17680533c19/web3js-ext/example/accountKey/AccountKeyPublic_01_accountUpdate.js#L18
**To-be**
```js
const { getPublicKeyFromPrivate } = require("@klaytn/js-ext-core");
const { getPublicKeyFromPrivate } = require("@klaytn/ethers-ext"); // because ethers-ext exports js-ext-core/util/*
const { getPublicKeyFromPrivate } = require("@klaytn/web3js-ext"); // because web3js-ext exports …
```

jscore: Add getPublicKeyFromPrivate

---

web3py-ext/web3py_ext/transaction/fee_delegation/fee_delegated_account_update_transaction.py
web3py-ext/web3py_ext/transaction/fee_delegation/fee_delegated_cancel_transaction.py
web3py-ext/web3py_ext/transaction/fee_delegation/fee_delegated_chaindata_anchoring_transaction.py
web3py-ext/web3py_ext/transaction/fee_delegation/fee_delegated_smart_contract_deploy_transaction.py
web3py-ext/web3py_ext/transaction/fee_delegation/fee_delegated_smart_contract_execution_transaction.py
web3py-ext/web3py_ext/transaction/fee_delegation/fee_delegated_value_transfer_transaction.py
web3py-ext/web3py_ext/transaction/fee_delegation/fee_delegated_value_transfer_with_memo_transaction.py

- web3py-ext
- feePayer dummy data case occurs when a user sign the transaction with Kaikas

added exception handling when dummy feepayer signature is in

---

.github/workflows/publish.yml
.github/workflows/testing.yml
ethers-ext/.eslintrc.js
ethers-ext/package-lock.json

Make the `testing` job run when PR is opened, reopened, and commits added. (previously only when opened)
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
> By default, a workflow only runs when a pull_request event's activity type is opened, synchronize, or reopened. 
https://github.com/orgs/community/discussions/24567
> if you push a new commit to the HEAD ref of a pull request then this “synchronize” event will be triggered.

ci: Run testing job whenever commits added to PR

---

ethers-ext/test/keystore.spec.ts
web3js-ext/README.md
web3js-ext/src/accounts/create.ts
web3js-ext/src/accounts/index.ts
web3js-ext/src/accounts/wallet.ts
web3js-ext/src/types.ts
web3js-ext/test/account.spec.ts

- `web3.eth.accounts.decrypt` can parse v4, return the first account.
- `web3.eth.accounts.decryptList` can parse v4, return all accounts.
- `web3.eth.accounts.wallet.decrypt` explicitly throws when v4 is given.
- Why not support v4? because web3 wallet uniquely identifies an account by its address. It’s confusing to support (1 address + many keys). We will not support v4 keystore until we have a good solution (e.g. AccountStore).

web3js: Keystore v4 (KIP-3) support

---

ethers-ext/example/accountKey/AccountKeyLegacy.js
js-ext-core/src/accountkey/accountkey.ts
js-ext-core/src/accountkey/factory.ts
js-ext-core/src/field/account.ts
js-ext-core/src/field/fieldset.ts
js-ext-core/src/tx/factory.ts
js-ext-core/src/util/const.ts
js-ext-core/src/util/data.ts
js-ext-core/test/accountkey.spec.ts
js-ext-core/test/tx.spec.ts
js-ext-core/test/util.spec.ts

- Add `parseAccountKey(rlp) -> object`
- AccountKeyWeightedMultiSig now accepts both representations:
```js
// array-of-objects: Recommended format
{
type: 4,
threshold: 2,
keys: [
{ weight: 1, key: "0x02c734b50ddb229be5e929fc4aa8080ae8240a802d23d3290e5e6156ce029b110e" },
{ weight: 1, key: "0x0212d45f1cc56fbd6cd8fc877ab63b5092ac77db907a8a42c41dad3e98d7c64dfb" },
]
}
```
```js
// array-of-tuples: Supported for backward compatibility
{
type: 4,
threshold: 2,
keys: [
[1, "0x02c734b50ddb229be5e929fc4aa8080ae8240a802d23d3290e5e6156ce029b110e"],
[1, "0x0212d45f1cc56fbd6cd8fc877ab63b5092ac77db907a8a42c41dad3e98d7c64dfb"],
]
}
```
- Fix `parseTransaction` to return numeric fields in proper format
- not `0x` but `0x0`
- not BigNumber but hex strings
- Fix `parseTxType` to accept bigint and null …

jscore: Add parseAccountKey, Fix parseTransaction and parseTxType

---

web3rpc/rpc-specs/paths/debug/blockchainInspection/preimage.yaml
web3rpc/rpc-specs/paths/debug/others/storageRangeAt.yaml

- Fix example output of debug_storageRangeAt
- Add notes that debug_preimage and debug_storageRangeAt are affected when preimages are not available.

rpc: Add notes to debug_preimage and debug_storageRangeAt
