klaytn/web3klaytn

api/paths/klay/transaction/estimateComputationCost.yaml

fix: fix required in parameters in klay_estimateComputationCost

fix: fix required in parameters in klay_estimateComputationCost

---

api/code-samples/curl/klay/account/createAccessList.sh
api/klay.yaml
api/paths/klay/account/createAccessList.yaml
api/paths/klay/index.yaml

feat: create rpc spec for klay_createAccessList

feat: create rpc spec for klay_createAccessList

---

api/code-samples/curl/klay/other/nodeAddress.sh
api/klay.yaml
api/paths/klay/index.yaml
api/paths/klay/other/nodeAddress.yaml

feat: create rpc spec for klay_nodeAddress

feat: create rpc spec for klay_nodeAddress

---

api/code-samples/curl/klay/other/getRawTransactionByHash.sh
api/klay.yaml
api/paths/klay/index.yaml
api/paths/klay/other/getRawTransactionByHash.yaml

Feat: create rpc spec for klay get raw transaction by hash

Feat: create rpc spec for klay get raw transaction by hash

---

api/code-samples/curl/klay/filter/getLogs.sh
api/code-samples/curl/klay/filter/unsubscribe.sh
api/components/schemas/common/Common.yaml
api/klay.yaml
api/paths/klay/filter/getLogs.yaml
api/paths/klay/filter/unsubscribe.yaml
api/paths/klay/index.yaml
api/paths/klay/other/resend.yaml

Feat: create rpc spec for klay_resend and klay_getlogs and klay_unsubcribe

Feat: create rpc spec for klay_resend and klay_getlogs and klay_unsubcribe

---

api/code-samples/curl/klay/block/getBlockWithConsensusInfoByNumberRange.sh
api/code-samples/curl/klay/configuration/getChainConfig.sh
api/code-samples/curl/klay/gas/lowerBoundGasPrice.sh
api/code-samples/curl/klay/gas/upperBoundGasPrice.sh
api/code-samples/curl/klay/others/getRawTransactionByBlockNumberAndIndex.sh
api/code-samples/curl/klay/others/getStakingInfo.sh
api/code-samples/curl/klay/transaction/pendingTransactions.sh
api/components/schemas/common/Common.yaml
api/klay.yaml
api/paths/klay/block/getBlockWithConsensusInfoByNumberRange.yaml
api/paths/klay/configuration/getChainConfig.yaml
api/paths/klay/gas/lowerBoundGasPrice.yaml
api/paths/klay/gas/upperBoundGasPrice.yaml
api/paths/klay/index.yaml
api/paths/klay/others/getRawTransactionByBlockNumberAndIndex.yaml
api/paths/klay/others/getStakingInfo.yaml
api/paths/klay/transaction/pendingTransactions.yaml
site/namespace/eth-openapi.yaml
site/namespace/klay-openapi.yaml

feat: create pending rpc

---

api/paths/eth/transaction/call.yaml
api/paths/klay/configuration/gasPriceAt.yaml

fix: add description for response

fix: add description for response

---

api/components/schemas/common/Common.yaml
api/paths/klay/account/getCode.yaml
api/paths/klay/block/getBlockTransactionCountByHash.yaml
api/paths/klay/block/getCouncil.yaml

Fix: fix bugs spelling in rpc spec

Fix: fix bugs spelling in rpc spec

---

api/code-samples/javascript/klay/block/getBlockTransactionCountByHash.js
api/code-samples/javascript/klay/block/getBlockWithConsensusInfoByNumber.js
api/code-samples/javascript/klay/block/getCouncilSize.js
api/code-samples/javascript/klay/block/getHeaderByHash.js
api/code-samples/javascript/klay/block/getHeaderByNumber.js
api/code-samples/javascript/klay/block/getRewards.js
api/code-samples/javascript/klay/block/getStorageAt.js
api/code-samples/javascript/klay/transaction/getDecodedAnchoringTransactionByHash.js
api/paths/klay/block/getBlockTransactionCountByHash.yaml
api/paths/klay/block/getCouncilSize.yaml
api/paths/klay/block/getHeaderByHash.yaml
api/paths/klay/block/getHeaderByNumber.yaml
api/paths/klay/block/getRewards.yaml
api/paths/klay/block/getStorageAt.yaml
api/paths/klay/transaction/getDecodedAnchoringTransactionByHash.yaml
sdk/client/javascript/openapi-test/test/constant.js
sdk/client/javascript/openapi-test/test/klay/account/KlayGetAccountKeyApi.test.js
sdk/client/javascript/openapi-test/test/klay/block/KlayGetCouncilSizeApi.test.js
sdk/client/javascript/openapi-test/test/klay/block/KlayGetHeaderByHashApi.test.js
sdk/client/javascript/openapi-test/test/klay/block/KlayGetHeaderByNumberApi.test.js
sdk/client/javascript/openapi-test/test/klay/block/KlayGetRewardsApi.test.js
sdk/client/javascript/openapi-test/test/klay/block/KlayGetStorageAtApi.test.js
sdk/client/javascript/openapi-test/test/klay/filter/KlayGetFilterChangesApi.test.js
sdk/client/javascript/openapi-test/test/klay/filter/KlayGetFilterLogsApi.test.js
sdk/client/javascript/openapi-test/test/klay/transaction/KlayGetDecodedAnchoringTransactionByHashApi.test.js
sdk/client/javascript/openapi-test/test/klay/transaction/KlayGetTransactionByBlockHashAndIndexApi.test.js
sdk/client/javascript/openapi-test/test/klay/transaction/KlayGetTransactionByBlockNumberAndIndexApi.test.js
sdk/client/javascript/openapi-test/test/klay/transaction/KlayGetTransactionByHashApi.test.js
sdk/client/javascript/openapi-test/test/klay/transaction/KlayGetTransactionBySenderTxHashApi.test.js

feat: js test for klay accounts, blocks, transaction

Feat: js test for klay accounts, blocks, transaction

---

api/paths/klay/block/getBlockByNumber.yaml
api/paths/klay/configuration/gasPrice.yaml
api/paths/klay/configuration/gasPriceAt.yaml

fix: fix description in response

fix: fix description in response

---

api/components/schemas/common/Common.yaml
sdk/client/javascript/openapi-test/jest.config.js
sdk/client/javascript/openapi-test/test/klay/account/KlayGetAccountKeyApi.test.js
sdk/client/javascript/openapi-test/test/klay/block/KlayGetBlockByHashApi.test.js
sdk/client/javascript/openapi-test/test/klay/block/KlayGetCommitteeApi.test.js
sdk/client/javascript/openapi-test/test/klay/block/KlayGetCommitteeSizeApi.test.js
sdk/client/javascript/openapi-test/test/klay/block/KlayGetCouncilApi.test.js
sdk/client/javascript/openapi-test/test/klay/block/KlayGetCouncilSizeApi.test.js
sdk/client/javascript/openapi-test/test/klay/gas/KlayFeeHistoryApi.test.js
sdk/client/javascript/openapi-test/test/klay/transaction/KlayGetTransactionByBlockHashAndIndexApi.test.js
sdk/client/javascript/openapi-test/test/klay/transaction/KlayGetTransactionByBlockNumberAndIndexApi.test.js
sdk/client/javascript/openapi-test/test/klay/transaction/KlayGetTransactionByHashApi.test.js
sdk/client/javascript/openapi-test/test/klay/transaction/KlayGetTransactionBySenderTxHashApi.test.js
sdk/client/javascript/template/libraries/javascript/api.mustache

Fix: klay get block by hash

---

api/code-samples/javascript/klay/block/getBlockWithConsensusInfoByNumberRange.js
api/code-samples/javascript/klay/transaction/getRawTransactionByBlockHashAndIndex.js
api/code-samples/javascript/klay/transaction/getRawTransactionByBlockNumberAndIndex.js
api/code-samples/javascript/klay/transaction/getRawTransactionByHash.js
api/paths/klay/block/getBlockWithConsensusInfoByNumberRange.yaml
api/paths/klay/others/getRawTransactionByBlockHashAndIndex.yaml
api/paths/klay/others/getRawTransactionByBlockNumberAndIndex.yaml
api/paths/klay/others/getRawTransactionByHash.yaml
sdk/client/javascript/openapi-test/test/klay/account/KlayGetAccountKeyApi.test.js
sdk/client/javascript/openapi-test/test/klay/block/KlayGetBlockWithConsensusInfoByNumberRangeApi.test.js
sdk/client/javascript/openapi-test/test/klay/transaction/KlayGetRawTransactionByBlockHashAndIndexApi.test.js
sdk/client/javascript/openapi-test/test/klay/transaction/KlayGetRawTransactionByBlockNumberAndIndexApi.test.js
sdk/client/javascript/openapi-test/test/klay/transaction/KlayGetRawTransactionByHashApi.test.js

Feat: js test and code-sample for transaction and block

Feat: js test and code-sample for transaction and block

---

api/paths/klay/account/isContractAccount.yaml
api/paths/klay/configuration/isSenderTxHashIndexingEnabled.yaml
api/paths/klay/configuration/maxPriorityFeePerGas.yaml
api/paths/klay/others/createAccessList.yaml

Fix: fix bugs description in rpc response

Fix: fix bugs description in rpc response

---

api/paths/klay/account/getTransactionCount.yaml
api/paths/klay/others/getStakingInfo.yaml
api/paths/klay/transaction/getTransactionBySenderTxHash.yaml
api/paths/klay/transaction/getTransactionReceipt.yaml

fix: fix bugs number 22, 36,37,38

fix: fix bugs number 22, 36,37,38

---

api/code-samples/javascript/klay/account/getTransactionCount.js
api/code-samples/javascript/klay/account/isContractAccount.js
api/code-samples/javascript/klay/configuration/isParallelDBWrite.js
api/code-samples/javascript/klay/configuration/isSenderTxHashIndexingEnabled.js
api/code-samples/javascript/klay/transaction/getTransactionReceiptBySenderTxHash.js
api/paths/klay/account/getTransactionCount.yaml
api/paths/klay/account/isContractAccount.yaml
api/paths/klay/configuration/isParallelDBWrite.yaml
api/paths/klay/configuration/isSenderTxHashIndexingEnabled.yaml
api/paths/klay/index.yaml
api/paths/klay/transaction/getTransactionReceiptBySenderTxHash.yaml
sdk/client/javascript/openapi-test/test/klay/account/KlayGetTransactionCountApi.test.js
sdk/client/javascript/openapi-test/test/klay/account/KlayIsContractAccountApi.test.js
sdk/client/javascript/openapi-test/test/klay/configuration/KlayIsParallelDBWriteApi.test.js
sdk/client/javascript/openapi-test/test/klay/configuration/KlayIsSenderTxHashIndexingEnabledApi.test.js
sdk/client/javascript/openapi-test/test/klay/transaction/KlayGetTransactionReceiptApi.test.js
sdk/client/javascript/openapi-test/test/klay/transaction/KlayGetTransactionReceiptBySenderTxHashApi.test.js

Feat: js test for configuration, transaction and account

Feat: js test for configuration, transaction and account

---

api/code-samples/curl/eth/account/sign.sh
api/code-samples/curl/eth/block/syncing.sh
api/code-samples/curl/eth/filter/uninstallFilter.sh
api/code-samples/curl/eth/miscellaneous/submitWork.sh
api/code-samples/curl/eth/transaction/sendRawTransaction.sh
api/code-samples/curl/eth/transaction/sendTransaction.sh
api/code-samples/curl/eth/transaction/signTransaction.sh
api/components/schemas/common/Common.yaml
api/klay.yaml
api/paths/eth/account/sign.yaml
api/paths/eth/block/syncing.yaml
api/paths/eth/filter/uninstallFilter.yaml
api/paths/eth/index.yaml
api/paths/eth/miscellaneous/submitWork.yaml
api/paths/eth/transaction/sendRawTransaction.yaml
api/paths/eth/transaction/sendTransaction.yaml
api/paths/eth/transaction/signTransaction.yaml

Feat: create rpc spec from 122 to 128

Feat: create rpc spec from 122 to 128

---

api/paths/klay/others/getRawTransactionByHash.yaml

fix: fix params in rpc klay_getRawTransactionByHash

fix: fix params in rpc klay_getRawTransactionByHash

---

api/code-samples/javascript/klay/block/getCommitteeSize.js
api/code-samples/javascript/klay/block/getCouncilSize.js
api/code-samples/javascript/klay/transaction/getDecodedAnchoringTransactionByHash.js

Fix: js sample code

---

api/code-samples/javascript/klay/block/getCommitteeSize.js
api/code-samples/javascript/klay/block/getCouncilSize.js

Fix: js-sample-code

---

api/paths/klay/account/getAccountKey.yaml

fix: add required to result type in klay_getAccountKey

fix: add required to result type in klay_getAccountKey

---

api/code-samples/javascript/klay/filter/getLogs.js
api/code-samples/javascript/klay/filter/uninstallFilter.js
api/code-samples/javascript/klay/miscellaneous/sha3.js
api/paths/klay/filter/getLogs.yaml
api/paths/klay/filter/uninstallFilter.yaml
api/paths/klay/index.yaml
api/paths/klay/miscellaneous/sha3.yaml
sdk/client/javascript/openapi-test/test/klay/account/KlaySignApi.test.js
sdk/client/javascript/openapi-test/test/klay/block/KlaySyncingApi.test.js
sdk/client/javascript/openapi-test/test/klay/filter/KlayGetLogsApi.test.js
sdk/client/javascript/openapi-test/test/klay/filter/KlaySubcribeApi.test.js
sdk/client/javascript/openapi-test/test/klay/filter/KlayUninstallFilterApi.test.js
sdk/client/javascript/openapi-test/test/klay/filter/KlayUnsubscribeApi.test.js
sdk/client/javascript/openapi-test/test/klay/miscellaneous/KlaySha3Api.test.js
sdk/client/javascript/openapi-test/test/klay/transaction/KlaySignTransactionApi.test.js
sdk/client/javascript/openapi-test/test/klay/transaction/KlaySignTransactionAsFeePayerApi.test.js

Feat: js test and sample code

---

api/code-samples/curl/net/listening.sh
api/code-samples/curl/net/networkID.sh
api/code-samples/curl/net/peerCount.sh
api/code-samples/curl/net/peerCountByType.sh
api/code-samples/curl/net/version.sh
api/klay.yaml
api/paths/net/index.yaml
api/paths/net/listening.yaml
api/paths/net/networkID.yaml
api/paths/net/peerCount.yaml
api/paths/net/peerCountByType.yaml
api/paths/net/version.yaml

feat: Create rpc spec for net

---

api/code-samples/curl/txpool/content.sh
api/code-samples/curl/txpool/inspect.sh
api/code-samples/curl/txpool/status.sh
api/klay.yaml
api/paths/txpool/content.yaml
api/paths/txpool/index.yaml
api/paths/txpool/inspect.yaml
api/paths/txpool/status.yaml

feat: create rpc spec for txpool

feat: create rpc spec for txpool

---

api/components/schemas/common/Common.yaml
api/paths/klay/account/isContractAccount.yaml
api/paths/klay/transaction/getTransactionByBlockHashAndIndex.yaml
api/paths/klay/transaction/getTransactionReceiptBySenderTxHash.yaml

fix: fix some bugs in klay

---

api/paths/klay/filter/getFilterChanges.yaml
api/paths/klay/filter/newFilter.yaml

fix: fix bug klay_getFilterChanges

fix: fix bug klay_getFilterChanges

---

api/paths/net/index.yaml
api/redocly/generate-namespace.sh
api/redocly/redocly.yaml
sdk/client/javascript/javascript-generate.sh
sdk/client/javascript/opensdk/src/index.js
sdk/client/javascript/scripts/net/javascript-net-generate.sh
sdk/client/javascript/scripts/net/net-config.yaml
sdk/client/javascript/scripts/txpool/javascript-txpool-generate.sh
sdk/client/javascript/scripts/txpool/txpool-config.yaml

Feat: update sdk for javascript add: net, txpool

Feat: update sdk for javascript add: net, txpool

---

api/components/schemas/common/KlaytnTransactionTypes.yaml
api/paths/klay/account/encodeAccountKey.yaml
api/paths/klay/account/getAccount.yaml
api/paths/klay/configuration/protocolVersion.yaml
api/paths/klay/configuration/rewardBase.yaml
api/paths/klay/transaction/getTransactionReceiptBySenderTxHash.yaml
api/paths/klay/transaction/sendRawTransaction.yaml
api/paths/klay/transaction/sendTransaction.yaml

fix: fix rpc klay_getAccountKey, getTransactionReceiptBySentTxHash

fix: fix rpc klay_getAccountKey, getTransactionReceiptBySentTxHash

---

api/paths/klay/block/syncing.yaml
api/paths/klay/configuration/isParallelDBWrite.yaml
api/paths/klay/configuration/isSenderTxHashIndexingEnabled.yaml
api/paths/klay/filter/uninstallFilter.yaml
api/paths/klay/miscellaneous/sha3.yaml
api/paths/klay/transaction/sendTransactionAsFeePayer.yaml
api/paths/klay/transaction/signTransaction.yaml

fix: fix bugs for rpc from index 67 to 73

fix: fix bugs for rpc from index 67 to 73

---

api/components/schemas/common/Common.yaml
api/paths/eth/block/blockNumber.yaml
api/paths/eth/config/chainId.yaml
api/paths/eth/config/coinbase.yaml
api/paths/eth/gas/feeHistory.yaml
api/paths/eth/transaction/estimateGas.yaml
api/paths/eth/transaction/fillTransaction.yaml
api/paths/klay/transaction/signTransactionAsFeePayer.yaml

fix: fix bugs in rpc spec from index 79 to 88

fix: fix bugs in rpc spec from index 79 to 88

---

api/components/schemas/common/Common.yaml
api/components/schemas/common/KlaytnTransactionTypes.yaml
api/paths/eth/block/getBlockByHash.yaml
api/paths/klay/filter/subscribe.yaml
api/paths/klay/transaction/getTransactionReceiptBySenderTxHash.yaml
api/paths/klay/transaction/signTransactionAsFeePayer.yaml

fix: fix bugs in klay_getFilterChanges and some klay rpc

fix: fix bugs in klay_getFilterChanges and some klay rpc

---

api/code-samples/javascript/klay/block/getBlockWithConsensusInfoByHash.js
api/code-samples/javascript/klay/configuration/getChainConfig.js
api/code-samples/javascript/klay/others/createAccessList.js
api/code-samples/javascript/klay/others/getStakingInfo.js
api/paths/klay/block/getBlockWithConsensusInfoByHash.yaml
api/paths/klay/configuration/getChainConfig.yaml
api/paths/klay/others/createAccessList.yaml
api/paths/klay/others/getStakingInfo.yaml
sdk/client/javascript/openapi-test/test/klay/block/KlayGetBlockWithConsensusInfoByHashApi.test.js
sdk/client/javascript/openapi-test/test/klay/configuration/KlayGetChainConfigApi.test.js
sdk/client/javascript/openapi-test/test/klay/others/KlayCreateAccessListApi.test.js
sdk/client/javascript/openapi-test/test/klay/others/KlayGetStakingInfoApi.test.js

Feat: add js test and sample code

Feat: add js test and sample code

---

api/code-samples/curl/klay/configuration/rewardBase.sh
api/code-samples/curl/klay/miscellaneous/sha3.sh
api/paths/eth/block/getHeaderByHash.yaml
api/paths/klay/block/getHeaderByHash.yaml
api/paths/klay/filter/getLogs.yaml
api/paths/klay/filter/newFilter.yaml
api/paths/klay/filter/subscribe.yaml
api/paths/klay/transaction/getDecodedAnchoringTransactionByHash.yaml

fix: fix klay_rewardbase, klay_sha3 and other some rpc spec

fix: fix klay_rewardbase, klay_sha3 and other some rpc spec

---

api/code-samples/javascript/klay/account/getCode.js
api/paths/klay/account/getCode.yaml
sdk/client/javascript/openapi-test/test/klay/account/KlayEncodeAccountKeyApi.test.js
sdk/client/javascript/openapi-test/test/klay/account/KlayGetCodeApi.test.js
sdk/client/javascript/openapi-test/test/klay/block/KlayGetBlockReceiptsApi.test.js
sdk/client/javascript/openapi-test/test/klay/transaction/KlayGetRawTransactionByHashApi.test.js
sdk/client/javascript/openapi-test/test/klay/transaction/KlayGetTransactionByBlockNumberAndIndexApi.test.js
sdk/client/javascript/openapi-test/test/klay/transaction/KlayGetTransactionByHashApi.test.js

Feat: update js and sample code

Feat: update js and sample code

---

api/code-samples/javascript/eth/account/getBalance.js
api/code-samples/javascript/eth/config/chainID.js
api/code-samples/javascript/eth/config/coinbase.js
api/code-samples/javascript/eth/config/gasPrice.js
api/code-samples/javascript/eth/gas/feeHistory.js
api/code-samples/javascript/eth/transaction/estimateGas.js
api/code-samples/javascript/eth/transaction/fillTransaction.js
api/paths/eth/account/getBalance.yaml
api/paths/eth/config/chainId.yaml
api/paths/eth/config/coinbase.yaml
api/paths/eth/config/gasPrice.yaml
api/paths/eth/gas/feeHistory.yaml
api/paths/eth/transaction/estimateGas.yaml
api/paths/eth/transaction/fillTransaction.yaml
sdk/client/javascript/openapi-test/test/eth/account/EthGetBalanceApi.test.js
sdk/client/javascript/openapi-test/test/eth/block/EthGetBlockByHashApi.test.js
sdk/client/javascript/openapi-test/test/eth/block/EthGetBlockByNumber.test.js
sdk/client/javascript/openapi-test/test/eth/config/EthChainIDApi.test.js
sdk/client/javascript/openapi-test/test/eth/config/EthCoinBaseApi.test.js
sdk/client/javascript/openapi-test/test/eth/config/EthGasPriceApi.test.js
sdk/client/javascript/openapi-test/test/eth/gas/EthEstimateGas.test.js
sdk/client/javascript/openapi-test/test/eth/gas/EthFeeHistoryApi.test.js
sdk/client/javascript/openapi-test/test/eth/transaction/EthFillTransactionApi.test.js

Feat: js test 81 to 90

---

api/code-samples/curl/eth/config/etherbase.sh
api/code-samples/curl/eth/filter/getLogs.sh
api/code-samples/curl/eth/filter/subscribe.sh
api/code-samples/curl/eth/filter/unsubscribe.sh
api/code-samples/curl/eth/miscellaneous/submitHashrate.sh
api/components/schemas/common/Common.yaml
api/klay.yaml
api/paths/eth/config/etherbase.yaml
api/paths/eth/filter/getLogs.yaml
api/paths/eth/filter/subscribe.yaml
api/paths/eth/filter/unsubscribe.yaml
api/paths/eth/index.yaml
api/paths/eth/miscellaneous/submitHashrate.yaml
api/paths/klay/filter/subscribe.yaml

feat: create rpc spec from index 133 to 137

feat: create rpc spec from index 133 to 137

---

api/code-samples/javascript/eth/account/getCode.js
api/code-samples/javascript/eth/block/getBlockTransactionCountByHash.js
api/code-samples/javascript/eth/block/getHeaderByHash.js
api/code-samples/javascript/eth/block/getHeaderByNumber.js
api/paths/eth/block/getBlockTransactionCountByHash.yaml
api/paths/eth/block/getHeaderByHash.yaml
api/paths/eth/block/getHeaderByNumber.yaml
sdk/client/javascript/openapi-test/test/eth/account/EthGetCodeApi.test.js
sdk/client/javascript/openapi-test/test/eth/block/EthGetBlockTransactionCountByHashApi.test.js
sdk/client/javascript/openapi-test/test/eth/block/EthGetBlockTransactionCountByNumberApi.test.js
sdk/client/javascript/openapi-test/test/eth/block/EthGetHeaderByHashApi.test.js
sdk/client/javascript/openapi-test/test/eth/block/EthGetHeaderByNumberApi.test.js
sdk/client/javascript/openapi-test/test/eth/filter/EthGetFilterChangesApi.test.js
sdk/client/javascript/openapi-test/test/eth/filter/EthGetFilterLogsApi.test.js

Feat: js test 91 to 97

---

api/code-samples/javascript/eth/block/getStorageAt.js
api/code-samples/javascript/eth/block/getUncleByBlockHashAndIndex.js
api/code-samples/javascript/eth/block/getUncleByBlockNumberAndIndex.js
api/code-samples/javascript/eth/transaction/getTransactionCount.js
api/code-samples/javascript/eth/transaction/getTransactionReceipt.js
api/paths/eth/block/getStorageAt.yaml
api/paths/eth/block/getUncleByBlockHashAndIndex.yaml
api/paths/eth/block/getUncleByBlockNumberAndIndex.yaml
api/paths/eth/transaction/getTransactionCount.yaml
api/paths/eth/transaction/getTransactionReceipt.yaml
sdk/client/javascript/openapi-test/test/eth/account/EthGetTransactionCountApi.test.js
sdk/client/javascript/openapi-test/test/eth/block/EthGetStorageAtApi.test.js
sdk/client/javascript/openapi-test/test/eth/block/EthGetUncleByBlockHashAndIndexApi.test.js
sdk/client/javascript/openapi-test/test/eth/block/EthGetUncleByBlockNumberAndIndexApi.test.js
sdk/client/javascript/openapi-test/test/eth/transaction/EthGetTransactionByBlockHashAndIndexApi.test.js
sdk/client/javascript/openapi-test/test/eth/transaction/EthGetTransactionByBlockNumberAndIndexApi.test.js
sdk/client/javascript/openapi-test/test/eth/transaction/EthGetTransactionByHashApi.test.js
sdk/client/javascript/openapi-test/test/eth/transaction/EthGetTransactionReceiptApi.test.js

Feat: add js test and sample code for rpc 102 to 109

Feat: add js test and sample code for rpc 102 to 109

---

api/code-samples/curl/eth/others/createAccessList.sh
api/code-samples/curl/eth/others/getRawTransactionByBlockHashAndIndex.sh
api/code-samples/curl/eth/others/getRawTransactionByBlockNumberAndIndex.sh
api/code-samples/curl/eth/others/getRawTransactionByHash.sh
api/klay.yaml
api/paths/eth/index.yaml
api/paths/eth/others/createAccessList.yaml
api/paths/eth/others/getRawTransactionByBlockHashAndIndex.yaml
api/paths/eth/others/getRawTransactionByBlockNumberAndIndex.yaml
api/paths/eth/others/getRawTransactionByHash.yaml
api/paths/klay/others/getRawTransactionByBlockNumberAndIndex.yaml

feat: create rpc spec eth create access list eth get raw transaction by hash

feat: create rpc spec eth create access list eth get raw transaction by hash

---

api/code-samples/curl/klay/others/resend.sh
api/paths/klay/others/nodeAddress.yaml
api/paths/klay/others/resend.yaml

fix: update rpc spec klay_nodeAddress and klay_resend

fix: update rpc spec klay_nodeAddress and klay_resend

---

api/code-samples/java/src/main/java/opensdk/sdk/apis/eth/account/EthGetBalanceExample.java
api/code-samples/java/src/main/java/opensdk/sdk/apis/eth/account/EthGetCodeExample.java
api/code-samples/java/src/main/java/opensdk/sdk/apis/eth/configuration/EthGasPriceExample.java
api/code-samples/java/src/main/java/opensdk/sdk/apis/klay/block/KlayGetCouncilSizeExample.java
api/code-samples/java/src/main/java/opensdk/sdk/apis/klay/gas/KlayMaxPriorityFeePerGasExample.java
api/paths/eth/account/getBalance.yaml
api/paths/eth/account/getCode.yaml
api/paths/eth/config/gasPrice.yaml
api/paths/klay/block/getBlockReceipts.yaml
api/paths/klay/gas/maxPriorityFeePerGas.yaml
sdk/client/java/openapi-test/src/test/java/opensdk/sdk/apis/eth/acount/EthAccountsApiTest.java
sdk/client/java/openapi-test/src/test/java/opensdk/sdk/apis/eth/acount/EthGetBalanceApiTest.java
sdk/client/java/openapi-test/src/test/java/opensdk/sdk/apis/eth/acount/EthGetCodeApiTest.java
sdk/client/java/openapi-test/src/test/java/opensdk/sdk/apis/eth/configuration/EthGasPriceApiTest.java
sdk/client/java/openapi-test/src/test/java/opensdk/sdk/apis/klay/block/KlayGetCouncilSizeApiTest.java
sdk/client/java/openapi-test/src/test/java/opensdk/sdk/apis/klay/gas/KlayMaxPriorityFeePerGasTest.java

feat: add unit test for apis eth

---

api/code-samples/javascript/eth/block/getUncleCountByBlockHash.js
api/code-samples/javascript/eth/block/getUncleCountByBlockNumber.js
api/code-samples/javascript/eth/block/mining.js
api/code-samples/javascript/eth/filter/newBlockFilter.js
api/code-samples/javascript/eth/filter/newPendingTransactionFilter.js
api/code-samples/javascript/eth/gas/maxPriorityFeePerGas.js
api/code-samples/javascript/eth/miscellaneous/hashRate.js
api/code-samples/javascript/eth/transaction/pendingTransactions.js
api/paths/eth/block/getUncleCountByBlockHash.yaml
api/paths/eth/block/getUncleCountByBlockNumber.yaml
api/paths/eth/block/mining.yaml
api/paths/eth/filter/newBlockFilter.yaml
api/paths/eth/filter/newPendingTransactionFilter.yaml
api/paths/eth/gas/maxPriorityFeePerGas.yaml
api/paths/eth/miscellaneous/hashRate.yaml
api/paths/eth/transaction/pendingTransactions.yaml
sdk/client/javascript/openapi-test/test/eth/block/EthGetUncleCountByBlockHashApi.test.js
sdk/client/javascript/openapi-test/test/eth/block/EthGetUncleCountByBlockNumberApi.test.js
sdk/client/javascript/openapi-test/test/eth/block/EthMiningApi.test.js
sdk/client/javascript/openapi-test/test/eth/filter/EthNewBlockFilterApi.test.js
sdk/client/javascript/openapi-test/test/eth/filter/EthNewFilterApi.test.js
sdk/client/javascript/openapi-test/test/eth/filter/EthNewPendingTransactionFilterApi.test.js
sdk/client/javascript/openapi-test/test/eth/gas/EthMaxPriorityFeePerGasApi.test.js
sdk/client/javascript/openapi-test/test/eth/miscellaneous/EthGetWorkApi.test.js
sdk/client/javascript/openapi-test/test/eth/miscellaneous/EthHashRateApi.test.js
sdk/client/javascript/openapi-test/test/eth/transaction/EthPendingTransactionsApi.test.js

Feat: js 110 to 119

---

api/paths/eth/account/getCode.yaml

Fix: js eth/getCode

---

api/code-samples/javascript/eth/config/etherbase.js
api/code-samples/javascript/eth/filter/getLogs.js
api/code-samples/javascript/eth/filter/uninstallFilter.js
api/code-samples/javascript/eth/miscellaneous/submitHashrate.js
api/code-samples/javascript/eth/transaction/getRawTransactionByBlockHashAndIndex.js
api/code-samples/javascript/eth/transaction/getRawTransactionByBlockNumberAndIndex.js
api/code-samples/javascript/eth/transaction/getRawTransactionByHash.js
api/paths/eth/config/etherbase.yaml
api/paths/eth/filter/getLogs.yaml
api/paths/eth/filter/uninstallFilter.yaml
api/paths/eth/miscellaneous/submitHashrate.yaml
api/paths/eth/others/getRawTransactionByBlockHashAndIndex.yaml
api/paths/eth/others/getRawTransactionByBlockNumberAndIndex.yaml
api/paths/eth/others/getRawTransactionByHash.yaml
sdk/client/javascript/openapi-test/test/eth/block/EthSyncingApi.test.js
sdk/client/javascript/openapi-test/test/eth/config/EthEtherBaseApi.test.js
sdk/client/javascript/openapi-test/test/eth/filter/EthGetLogsApi.test.js
sdk/client/javascript/openapi-test/test/eth/filter/EthUninstallFilterApi.test.js
sdk/client/javascript/openapi-test/test/eth/miscellaneous/EthSubmitHashrateApi.test.js
sdk/client/javascript/openapi-test/test/eth/transaction/EthGetRawTransactionByBlockHashAndIndexApi.test.js
sdk/client/javascript/openapi-test/test/eth/transaction/EthGetRawTransactionByBlockNumberAndIndexApi.test.js
sdk/client/javascript/openapi-test/test/eth/transaction/EthGetRawTransactionByHashApi.test.js

Feat: js test 99 to 127

---

api/paths/eth/others/getRawTransactionByHash.yaml

Fix: import yaml

---

LICENSE
README.md
UserGuide.md
bin/README.md
site/README.md

This PR removed old URLs and updated in README files.

Delete old URL

---

api/code-samples/javascript/net/listening.js
api/code-samples/javascript/net/networkID.js
api/code-samples/javascript/net/peerCount.js
api/code-samples/javascript/net/peerCountByType.js
api/code-samples/javascript/net/version.js
api/paths/net/listening.yaml
api/paths/net/networkID.yaml
api/paths/net/peerCount.yaml
api/paths/net/peerCountByType.yaml
api/paths/net/version.yaml
sdk/client/javascript/openapi-test/test/net/NetListeningApi.test.js
sdk/client/javascript/openapi-test/test/net/NetNetworkIdApi.test.js
sdk/client/javascript/openapi-test/test/net/NetPeerCountApi.test.js
sdk/client/javascript/openapi-test/test/net/NetPeerCountByTypeApi.test.js
sdk/client/javascript/openapi-test/test/net/NetVersionApi.test.js
sdk/client/javascript/opensdk/src/index.js

Feat: js test 129 to 136

---

api/code-samples/curl/eth/block/getUncleCountByBlockHash.sh
api/code-samples/curl/eth/transaction/signTransaction.sh
api/components/schemas/common/Common.yaml
api/klay.yaml
api/paths/eth/account/getBalance.yaml
api/paths/eth/account/sign.yaml
api/paths/eth/block/getBlockByHash.yaml
api/paths/eth/block/getUncleByBlockHashAndIndex.yaml
api/paths/eth/block/getUncleByBlockNumberAndIndex.yaml
api/paths/eth/block/getUncleCountByBlockHash.yaml
api/paths/eth/block/syncing.yaml
api/paths/eth/filter/newFilter.yaml
api/paths/eth/filter/uninstallFilter.yaml
api/paths/eth/miscellaneous/submitWork.yaml
api/paths/eth/others/getRawTransactionByBlockNumberAndIndex.yaml
api/paths/eth/others/getRawTransactionByHash.yaml
api/paths/eth/transaction/sendRawTransaction.yaml
api/paths/eth/transaction/signTransaction.yaml
api/paths/klay/block/getBlockWithConsensusInfoByHash.yaml
api/paths/klay/block/getBlockWithConsensusInfoByNumber.yaml
api/paths/klay/others/getRawTransactionByBlockNumberAndIndex.yaml
api/paths/klay/others/nodeAddress.yaml

fix: fix bugs in eth rpc spec

---

api/paths/eth/block/getUncleByBlockHashAndIndex.yaml
api/paths/eth/block/getUncleByBlockNumberAndIndex.yaml
api/paths/eth/block/getUncleCountByBlockHash.yaml

fix: fix type null in getUncleCountByBlockHash

fix: fix type null in getUncleCountByBlockHash

---

api/redocly/generate-namespace.sh
api/redocly/redocly.yaml
sdk/client/javascript/javascript-generate.sh
sdk/client/javascript/scripts/klaytnDebug/debug-config.yaml
sdk/client/javascript/scripts/klaytnDebug/javascript-debug-generate.sh

Feat: add debug generage for js

Feat: add debug generage for js

---

api/paths/eth/block/getBlockByNumber.yaml
api/paths/eth/transaction/fillTransaction.yaml
api/paths/eth/transaction/pendingTransactions.yaml
api/paths/eth/transaction/sendTransaction.yaml
api/paths/eth/transaction/signTransaction.yaml

fix: fix rpc eth_fillTransaction, eth_getBlockByNumber and some other eth rpc

fix: fix rpc eth_fillTransaction, eth_getBlockByNumber and some other eth rpc

---

api/code-samples/curl/klay/others/resend.sh
api/paths/klay/others/resend.yaml

fix: fix rpc klay_resend

---

sdk/client/javascript/template/libraries/javascript/ApiClient.mustache

Feat: update apiClient in js to skip validate response

Feat: update apiClient in js to skip validate response

---

api/code-samples/javascript/eth/block/getBlockByHash.js
api/code-samples/javascript/eth/block/getBlockByNumber.js
api/code-samples/javascript/eth/transaction/getTransactionByBlockHashAndIndex.js
api/code-samples/javascript/eth/transaction/getTransactionByBlockNumberAndIndex.js
api/code-samples/javascript/eth/transaction/getTransactionByHash.js
api/code-samples/javascript/klay/transaction/getTransactionReceipt.js
api/paths/eth/block/getBlockByHash.yaml
api/paths/eth/block/getBlockByNumber.yaml
api/paths/eth/transaction/getTransactionByBlockHashAndIndex.yaml
api/paths/eth/transaction/getTransactionByBlockNumberAndIndex.yaml
api/paths/eth/transaction/getTransactionByHash.yaml
api/paths/klay/transaction/getTransactionReceipt.yaml
sdk/client/javascript/javascript-generate.sh
sdk/client/javascript/openapi-test/test/eth/block/EthGetBlockByHashApi.test.js
sdk/client/javascript/openapi-test/test/eth/block/EthGetBlockByNumber.test.js
sdk/client/javascript/openapi-test/test/eth/others/EthCreateAccessListApi.test.js
sdk/client/javascript/openapi-test/test/eth/transaction/EthGetTransactionByBlockHashAndIndexApi.test.js
sdk/client/javascript/openapi-test/test/eth/transaction/EthGetTransactionByBlockNumberAndIndexApi.test.js
sdk/client/javascript/openapi-test/test/eth/transaction/EthGetTransactionByHashApi.test.js
sdk/client/javascript/openapi-test/test/klay/transaction/KlayGetTransactionReceiptApi.test.js

Fix: js pending unit test

---

api/code-samples/javascript/klay/account/getAccountKey.js
api/paths/klay/account/getAccountKey.yaml
sdk/client/javascript/openapi-test/test/klay/account/KlayGetAccountKeyApi.test.js

Fix: js klay_getAccountKey

---

api/code-samples/curl/eth/transaction/signTransaction.sh
api/components/schemas/common/KlaytnTransactionTypes.yaml
api/paths/eth/transaction/pendingTransactions.yaml
api/paths/eth/transaction/signTransaction.yaml
api/paths/klay/transaction/sendTransaction.yaml
api/paths/klay/transaction/sendTransactionAsFeePayer.yaml
api/paths/klay/transaction/signTransaction.yaml
api/paths/klay/transaction/signTransactionAsFeePayer.yaml
api/paths/personal/sendTransaction.yaml
api/paths/personal/signTransaction.yaml

fix: fix bugs in personal and some bugs in eth

fix: fix bugs in personal and some bugs in eth

---

api/code-samples/curl/eth/transaction/sendTransaction.sh
api/paths/eth/transaction/sendTransaction.yaml

fix: fix some bugs in eth and personal

fix: fix some bugs in eth and personal

---

api/code-samples/javascript/eth/block/syncing.js
api/code-samples/javascript/eth/filter/getFilterChanges.js
api/code-samples/javascript/eth/filter/getFilterLogs.js
api/code-samples/javascript/eth/miscellaneous/submitWork.js
api/code-samples/javascript/klay/block/syncing.js
api/code-samples/javascript/klay/filter/getFilterChanges.js
api/code-samples/javascript/klay/filter/getFilterLogs.js
api/paths/eth/block/syncing.yaml
api/paths/eth/filter/getFilterChanges.yaml
api/paths/eth/filter/getFilterLogs.yaml
api/paths/eth/miscellaneous/submitWork.yaml
api/paths/klay/block/syncing.yaml
api/paths/klay/filter/getFilterChanges.yaml
api/paths/klay/filter/getFilterLogs.yaml
sdk/client/javascript/openapi-test/helpers/eth.js
sdk/client/javascript/openapi-test/helpers/klay.js
sdk/client/javascript/openapi-test/test/eth/account/EthGetCodeApi.test.js
sdk/client/javascript/openapi-test/test/eth/block/EthSyncingApi.test.js
sdk/client/javascript/openapi-test/test/eth/filter/EthGetFilterLogsApi.test.js
sdk/client/javascript/openapi-test/test/eth/filter/EthNewFilterApi.test.js
sdk/client/javascript/openapi-test/test/eth/miscellaneous/EthSubmitWorkApi.test.js
sdk/client/javascript/openapi-test/test/klay/account/KlayGetCodeApi.test.js
sdk/client/javascript/openapi-test/test/klay/block/KlaySyncingApi.test.js
sdk/client/javascript/openapi-test/test/klay/filter/KlayGetFilterChangesApi.test.js
sdk/client/javascript/openapi-test/test/klay/filter/KlayGetFilterLogsApi.test.js

Feat: js pending test

---

api/paths/personal/index.yaml
api/redocly/generate-namespace.sh
api/redocly/redocly.yaml

Feat: add namespace personal for yaml

Feat: add namespace personal for yaml

---

api/code-samples/javascript/eth/filter/newFilter.js
api/code-samples/javascript/klay/filter/newFilter.js
api/paths/eth/filter/newFilter.yaml
sdk/client/javascript/openapi-test/helpers/eth.js
sdk/client/javascript/openapi-test/helpers/klay.js
sdk/client/javascript/openapi-test/test/eth/filter/EthGetFilterChangesApi.test.js
sdk/client/javascript/openapi-test/test/eth/filter/EthGetFilterLogsApi.test.js
sdk/client/javascript/openapi-test/test/eth/filter/EthNewFilterApi.test.js
sdk/client/javascript/openapi-test/test/klay/filter/KlayNewFilterApi.test.js

Fix: js fitler sdk pending fix

Fix: js filter sdk pending fix

---

api/code-samples/javascript/eth/transaction/sendRawTransaction.js
api/paths/eth/transaction/sendRawTransaction.yaml
api/paths/klay/transaction/sendRawTransaction.yaml
sdk/client/javascript/openapi-test/helpers/eth.js
sdk/client/javascript/openapi-test/test/eth/transaction/EthSendRawTransactionApi.test.js
sdk/client/javascript/openapi-test/test/klay/transaction/KlaySendRawTransactionApi.test.js

Feat: add js klay,eth sendRawTransaction

Feat: add js klay,eth sendRawTransaction

---

api/code-samples/curl/klaytnDebug/profiling/setBlockProfileRate.sh
api/code-samples/curl/klaytnDebug/profiling/writeMutexProfile.sh
api/code-samples/curl/personal/unlockAccount.sh
api/paths/klaytnDebug/blockchainInspection/preimage.yaml
api/paths/klaytnDebug/profiling/blockProfile.yaml
api/paths/klaytnDebug/profiling/cpuProfile.yaml
api/paths/klaytnDebug/profiling/mutexProfile.yaml
api/paths/klaytnDebug/profiling/setBlockProfileRate.yaml
api/paths/klaytnDebug/profiling/startCPUProfile.yaml
api/paths/klaytnDebug/profiling/stopCPUProfile.yaml
api/paths/klaytnDebug/profiling/writeBlockProfile.yaml
api/paths/klaytnDebug/profiling/writeMemProfile.yaml
api/paths/klaytnDebug/profiling/writeMutexProfile.yaml
api/paths/klaytnDebug/runtimeTracing/goTrace.yaml
api/paths/klaytnDebug/runtimeTracing/startGoTrace.yaml
api/paths/personal/signTransaction.yaml
api/paths/personal/unlockAccount.yaml
api/paths/txpool/content.yaml
api/paths/txpool/inspect.yaml
api/paths/txpool/status.yaml

fix: fix bugs from index 108 to 150

fix: fix bugs from index 108 to 150

---

api/code-samples/javascript/admin/addPeerApi.js
api/code-samples/javascript/admin/dataDirApi.js
api/code-samples/javascript/admin/exportChainApi.js
api/code-samples/javascript/admin/importChainApi.js
api/code-samples/javascript/admin/nodeInforApi.js
api/code-samples/javascript/admin/peersApi.js
api/code-samples/javascript/admin/removePeerApi.js
api/code-samples/javascript/admin/stateMigrationStatusApi.js
api/paths/admin/addPeer.yaml
api/paths/admin/datadir.yaml
api/paths/admin/exportChain.yaml
api/paths/admin/importChain.yaml
api/paths/admin/nodeInfo.yaml
api/paths/admin/peers.yaml
api/paths/admin/removePeer.yaml
api/paths/admin/stateMigrationStatus.yaml
sdk/client/javascript/openapi-test/test/admin/AdminAddPeerApi.test.js
sdk/client/javascript/openapi-test/test/admin/AdminDataDirApi.test.js
sdk/client/javascript/openapi-test/test/admin/AdminExportChainApi.test.js
sdk/client/javascript/openapi-test/test/admin/AdminImportChainApi.test.js
sdk/client/javascript/openapi-test/test/admin/AdminImportChainFromStringApi.test.js
sdk/client/javascript/openapi-test/test/admin/AdminNodeInforApi.test.js
sdk/client/javascript/openapi-test/test/admin/AdminPeersApi.test.js
sdk/client/javascript/openapi-test/test/admin/AdminRemovePeerApi.test.js
sdk/client/javascript/openapi-test/test/admin/AdminStateMigrationStatusApi.test.js

Feat: js test admin

---

api/code-samples/javascript/admin/startHTTP.js
api/code-samples/javascript/admin/stopHTTP.js
api/code-samples/javascript/eth/account/sign.js
api/code-samples/javascript/eth/transaction/sendTransaction.js
api/code-samples/javascript/eth/transaction/signTransaction.js
api/code-samples/javascript/klay/account/sign.js
api/code-samples/javascript/klay/transaction/sendTransaction.js
api/code-samples/javascript/klay/transaction/sendTransactionAsFeePayer.js
api/code-samples/javascript/klay/transaction/signTransaction.js
api/code-samples/javascript/klay/transaction/signTransactionAsFeePayer.js
api/paths/admin/startHTTP.yaml
api/paths/admin/stopHTTP.yaml
api/paths/eth/account/sign.yaml
api/paths/eth/transaction/sendTransaction.yaml
api/paths/eth/transaction/signTransaction.yaml
api/paths/klay/account/sign.yaml
api/paths/klay/transaction/sendTransaction.yaml
api/paths/klay/transaction/sendTransactionAsFeePayer.yaml
api/paths/klay/transaction/signTransaction.yaml
api/paths/klay/transaction/signTransactionAsFeePayer.yaml
sdk/client/javascript/openapi-test/helpers/eth.js
sdk/client/javascript/openapi-test/test/admin/AdminStartHTTPApi.test.js
sdk/client/javascript/openapi-test/test/admin/AdminStopHTTPApi.test.js
sdk/client/javascript/openapi-test/test/eth/transaction/EthSendTransactionApi.test.js
sdk/client/javascript/openapi-test/test/eth/transaction/EthSignApi.test.js
sdk/client/javascript/openapi-test/test/eth/transaction/EthSignTransactionApi.test.js
sdk/client/javascript/openapi-test/test/klay/transaction/KlaySendTransactionApi.test.js
sdk/client/javascript/openapi-test/test/klay/transaction/KlaySendTransactionAsFeePayerApi.test.js

Feat: js admin test and fix pending test

Feat: js admin test and fix pending test

---

api/code-samples/curl/admin/setMaxSubscriptionPerWSConn.sh
api/code-samples/curl/admin/startHTTP.sh
api/components/schemas/common/Common.yaml
api/paths/admin/nodeInfo.yaml
api/paths/admin/setMaxSubscriptionPerWSConn.yaml
api/paths/admin/startHTTP.yaml
api/paths/admin/stateMigrationStatus.yaml
api/paths/klay/account/decodeAccountKey.yaml
api/paths/klay/block/getBlockReceipts.yaml
api/paths/klay/block/getBlockWithConsensusInfoByNumberRange.yaml
api/paths/klay/block/getHeaderByHash.yaml
api/paths/klay/block/getHeaderByNumber.yaml
api/paths/klay/filter/unsubscribe.yaml
api/paths/klay/gas/feeHistory.yaml
api/paths/klay/others/createAccessList.yaml
api/paths/klay/transaction/getDecodedAnchoringTransactionByHash.yaml
api/paths/klay/transaction/getTransactionByHash.yaml
api/paths/klay/transaction/getTransactionBySenderTxHash.yaml
api/paths/klay/transaction/getTransactionReceipt.yaml
api/paths/klay/transaction/getTransactionReceiptBySenderTxHash.yaml
api/paths/klay/transaction/sendRawTransaction.yaml

fix: fix bugs common

---

api/code-samples/javascript/admin/getSpamThrottlerCandidateList.js
api/code-samples/javascript/admin/getSpamThrottlerThrottleList.js
api/code-samples/javascript/admin/getSpamThrottlerWhiteList.js
api/code-samples/javascript/admin/spamThrottlerConfig.js
api/code-samples/javascript/admin/startSpamThrottler.js
api/code-samples/javascript/admin/stopSpamThrottler.js
api/code-samples/javascript/klay/transaction/signTransaction.js
api/paths/admin/getSpamThrottlerCandidateList.yaml
api/paths/admin/getSpamThrottlerThrottleList.yaml
api/paths/admin/getSpamThrottlerWhiteList.yaml
api/paths/admin/index.yaml
api/paths/admin/spamThrottlerConfig.yaml
api/paths/admin/startSpamThrottler.yaml
api/paths/admin/stopSpamThrottler.yaml
sdk/client/javascript/openapi-test/test/admin/AdminGetSpamThrottlerCandidateListApi.test.js
sdk/client/javascript/openapi-test/test/admin/AdminGetSpamThrottlerThrottleListApi.test.js
sdk/client/javascript/openapi-test/test/admin/AdminGetSpamThrottlerWhiteListApi.test.js
sdk/client/javascript/openapi-test/test/admin/AdminSpamThrottlerConfigApi.test.js
sdk/client/javascript/openapi-test/test/admin/AdminStartSpamThrottlerApi.test.js
sdk/client/javascript/openapi-test/test/admin/AdminStopSpamThrottlerApi.test.js
sdk/client/javascript/openapi-test/test/klay/transaction/KlaySignTransactionApi.test.js

Feat: js admin unit test and samples

Feat: js admin unit test and samples

---

api/code-samples/javascript/admin/setSpamThrottlerWhiteList.js
api/code-samples/javascript/eth/block/getBlockTransactionCountByNumber.js
api/paths/admin/setSpamThrottlerWhiteList.yaml
api/paths/eth/block/getBlockTransactionCountByNumber.yaml
sdk/client/javascript/openapi-test/helpers/eth.js
sdk/client/javascript/openapi-test/test/admin/AdminSetSpamThrottlerWhiteListApi.test.js
sdk/client/javascript/openapi-test/test/klay/others/KlayResendApi.test.js
sdk/client/javascript/openapi-test/test/klay/transaction/KlayGetTransactionByHashApi.test.js

Fix: pending js test

---

codegen/src/main/kotlin/caver/sdk/KlaytnJavaClientCodegen.kt
sdk/client/java/template/KlayGetAccountKey.java.mustache
sdk/client/java/template/libraries/retrofit2/api.mustache
sdk/client/java/template/model.mustache
sdk/client/java/template/pojoSubModel.mustache

issueResolving

---

api/code-samples/java/src/main/java/opensdk/sdk/apis/klay/block/KlaySyncingExample.java
api/code-samples/java/src/main/java/opensdk/sdk/apis/klay/filter/KlayGetLogsExample.java
api/code-samples/java/src/main/java/opensdk/sdk/apis/klay/filter/KlayNewFilterExample.java
api/paths/klay/block/syncing.yaml
sdk/client/java/openapi-test/src/test/java/opensdk/sdk/apis/eth/filter/EthGetLogTest.java
sdk/client/java/openapi-test/src/test/java/opensdk/sdk/apis/eth/transaction/EthSendRawTransactionTest.java
sdk/client/java/openapi-test/src/test/java/opensdk/sdk/apis/klay/account/KlayEncodeAccountKeyApiTest.java
sdk/client/java/openapi-test/src/test/java/opensdk/sdk/apis/klay/block/KlaySyncingTest.java
sdk/client/java/openapi-test/src/test/java/opensdk/sdk/apis/klay/filter/KlayGetFilterLogsTest.java
sdk/client/java/openapi-test/src/test/java/opensdk/sdk/apis/klay/filter/KlayGetLogsTest.java
sdk/client/java/openapi-test/src/test/java/opensdk/sdk/apis/klay/filter/KlayNewFilterTest.java
sdk/client/java/openapi-test/src/test/java/opensdk/sdk/apis/klay/transaction/KlaySendRawTransactionTest.java

feat: java add unit test and sample code for rpcs 70-73-55

fix: java fix bug eth when gen new code

---

ethers-ext/example/accountKey/AccountKeyLegacy_03_signVerify.js
ethers-ext/package.json
ethers-ext/src/index.ts

Update package.json version and main path.
Verified that some examples work with https://www.npmjs.com/package/@blukat29/ethers-ext.

ethers: Update package.json

---

web3j-ext/README.md
web3j-ext/web3j-ext/build.gradle
web3j-ext/web3j-ext/src/main/java/org/web3j/crypto/KlayRawTransaction.java
web3j-ext/web3j-ext/src/main/java/org/web3j/crypto/KlayTransactionEncoder.java
web3j-ext/web3j-ext/src/main/java/org/web3j/example/FillTransactionExample.java
web3j-ext/web3j-ext/src/main/java/org/web3j/example/InteractWithContractAndFeeDelegateExample.java
web3j-ext/web3j-ext/src/main/java/org/web3j/example/SimpleStorage.java
web3j-ext/web3j-ext/src/main/java/org/web3j/example/SimpleStorage.sol
web3j-ext/web3j-ext/web3jext-generate.sh

- add fillTransaction and example 
- add example for interacting Contract with fee delegated Transaction
- a few changes in README 
- change web3j-ext gradle publish to include web3rpc
but still working on quickstart & verifyTransaction

a few fixes

---

ethers-ext/package.json
web3py-ext/setup.py

beta mark has been moved behind version

---

web3py-ext/web3py_ext/example/28-account_store.py
web3py-ext/web3py_ext/klaytn_account/account_store.py
web3py-ext/web3py_ext/klaytn_account/instrumented_local_account.py

- updated the account store example
- fixed a bug in treating address

checksum address bugfix

---

ethers-ext/package.json
web3j-ext/web3j-ext/build.gradle
web3py-ext/setup.py

version up to 0.9.1-beta

---

ethers-ext/example/smartContract/deploy_with_FeeDelegation.js
ethers-ext/example/smartContract/write_with_feeDelegation.js
ethers-ext/example/transactions/FeeDel_09_TxTypeFeeDelegatedValueTransfer.js
ethers-ext/example/transactions/FeeDel_09_TxTypeFeeDelegatedValueTransfer2.js
ethers-ext/example/transactions/FeeDel_11_TxTypeFeeDelegatedValueTransferMemo.js
ethers-ext/example/transactions/FeeDel_21_TxTypeFeeDelegatedAccountUpdate.js
ethers-ext/example/transactions/FeeDel_29_TxTypeFeeDelegatedSmartContractDeploy.js
ethers-ext/example/transactions/FeeDel_31_TxTypeFeeDelegatedSmartContractExecution.js
ethers-ext/example/transactions/FeeDel_39_TxTypeFeeDelegatedCancel.js
ethers-ext/example/transactions/PartialFeeDel_0a_TxTypeFeeDelegatedValueTransferWithRatio.js
ethers-ext/example/transactions/PartialFeeDel_12_TxTypeFeeDelegatedValueTransferMemoWithRatio.js
ethers-ext/example/transactions/PartialFeeDel_22_TxTypeFeeDelegatedAccountUpdateWithRatio.js
ethers-ext/example/transactions/PartialFeeDel_2a_TxTypeFeeDelegatedSmartContractDeployWithRatio.js
ethers-ext/example/transactions/PartialFeeDel_32_TxTypeFeeDelegatedSmartContractExecutionWithRatio.js
ethers-ext/example/transactions/PartialFeeDel_3a_TxTypeFeeDelegatedCancelWithRatio.js
ethers-ext/src/ethers/signer.ts

- Sign with senderTxHashRLP signTransactionAsFeePayer()
- Update examples

Sign with senderTxHashRLP

---

web3j-ext/README.md
web3j-ext/web3j-ext/src/main/java/org/web3j/crypto/transaction/type/AbstractTxType.java
web3j-ext/web3j-ext/src/main/java/org/web3j/crypto/transaction/type/TxTypeFeeDelegate.java
web3j-ext/web3j-ext/src/main/java/org/web3j/example/AccountUpdateExample.java
web3j-ext/web3j-ext/src/main/java/org/web3j/example/CancelExample.java
web3j-ext/web3j-ext/src/main/java/org/web3j/example/FeeDelegatedCancelExample.java
web3j-ext/web3j-ext/src/main/java/org/web3j/example/FeeDelegatedCancelWithRatioExample.java
web3j-ext/web3j-ext/src/main/java/org/web3j/example/FeeDelegatedSmartContractDeployExample.java
web3j-ext/web3j-ext/src/main/java/org/web3j/example/FeeDelegatedSmartContractDeployWithRatioExample.java
web3j-ext/web3j-ext/src/main/java/org/web3j/example/FeeDelegatedSmartContractExecutionExample.java
web3j-ext/web3j-ext/src/main/java/org/web3j/example/FeeDelegatedSmartContractExecutionWithRatio.java
web3j-ext/web3j-ext/src/main/java/org/web3j/example/FillTransactionExample.java
web3j-ext/web3j-ext/src/main/java/org/web3j/example/InteractWithContractAndFeeDelegateExample.java
web3j-ext/web3j-ext/src/main/java/org/web3j/example/KlayRawTransactionManagerExample.java
web3j-ext/web3j-ext/src/main/java/org/web3j/example/LegacyExample.java
web3j-ext/web3j-ext/src/main/java/org/web3j/example/SmartContractDeployExample.java
web3j-ext/web3j-ext/src/main/java/org/web3j/example/SmartContractExecutionExample.java
web3j-ext/web3j-ext/src/main/java/org/web3j/example/ValueTransferExample.java
web3j-ext/web3j-ext/src/main/java/org/web3j/example/ValueTransferMemoExample.java

fix javadoc error
```shell
error: @param name not found 
````
and change repo name in readme

fix javadoc and readme

---

ethers-ext/.eslintrc.js
ethers-ext/package.json
ethers-ext/src/core/field.ts
ethers-ext/src/core/klaytn_tx.ts
ethers-ext/src/core/util.ts
ethers-ext/src/ethers/accountStore.ts
ethers-ext/src/ethers/provider.ts
ethers-ext/src/ethers/signer.ts

ethers: lint: Fix logical rules

---

web3j-ext/web3j-ext/src/main/java/org/web3j/utils/KlayConvert.java

add convert logic

---

ethers-ext/package.json
web3py-ext/setup.py

version update to v0.9.2 for ethers and web3py

version update in ethers and web3py

---

web3js-ext/example/accountKey/AccountKeyLegacy_01_ValueTransfer.js
web3js-ext/example/accountKey/AccountKeyPublic_01_accountUpdate.js
web3js-ext/example/accountKey/AccountKeyPublic_02_valueTransfer.js
web3js-ext/example/accountKey/AccountKeyRoleBased_01_accountUpdate.js
web3js-ext/example/accountKey/AccountKeyRoleBased_02_valueTransfer.js
web3js-ext/example/accountKey/AccountKeyWeightedMultiSig_01_accountUpdate.js
web3js-ext/example/accountKey/AccountKeyWeightedMultiSig_02_valueTransfer.js
web3js-ext/example/transactions/FeeDel_09_TxTypeFeeDelegatedValueTransfer.js
web3js-ext/example/transactions/FeeDel_11_TxTypeFeeDelegatedValueTransferMemo.js
web3js-ext/example/transactions/FeeDel_21_TxTypeFeeDelegatedAccountUpdate.js
web3js-ext/example/transactions/FeeDel_29_TxTypeFeeDelegatedSmartContractDeploy.js
web3js-ext/example/transactions/FeeDel_31_TxTypeFeeDelegatedSmartContractExecution.js
web3js-ext/example/transactions/FeeDel_39_TxTypeFeeDelegatedCancel.js
web3js-ext/example/transactions/PartialFeeDel_0a_TxTypeFeeDelegatedValueTransferWithRatio.js
web3js-ext/example/transactions/PartialFeeDel_12_TxTypeFeeDelegatedValueTransferMemoWithRatio.js
web3js-ext/example/transactions/PartialFeeDel_22_TxTypeFeeDelegatedAccountUpdateWithRatio.js
web3js-ext/example/transactions/PartialFeeDel_2a_TxTypeFeeDelegatedSmartContractDeployWithRatio.js
web3js-ext/example/transactions/PartialFeeDel_32_TxTypeFeeDelegatedSmartContractExecutionWithRatio.js
web3js-ext/example/transactions/PartialFeeDel_3a_TxTypeFeeDelegatedCancelWithRatio.js
web3js-ext/src/web3/web3.ts

Add examples and Test each cases. 
- AccountKeyLegacy : ValueTransfer 
- AccountKeyPublic : AcountUpdate, ValueTransfer 
- AccountKeyWeightedMultiSig : AcountUpdate, ValueTransfer 
- AccountKeyRoleBased : AcountUpdate, ValueTransfer

Web3.js Ext AccountKey

---

ethers-ext/package.json
web3j-ext/web3j-ext/build.gradle
web3py-ext/setup.py
web3rpc/rpc-specs/package.json
web3rpc/sdk/client/java/java-config.yaml
web3rpc/sdk/client/javascript/javascript-config.yaml

Changes
- V4 Keystore support
- #506 
- #521 
- added recoverFromTransaction, recoverFromMessage examples
- #509

version up to v0.9.5-beta

---

web3j-ext/web3j-ext/build.gradle

fix for version up to 0.9.5-beta

fix:make web3j-ext use web3rpc-java-0.9.4

---

ethers-ext/package-lock.json
ethers-ext/src/ethers/signer.ts

Resolves https://github.com/klaytn/web3klaytn/issues/499.
Tested against a patched Klaytn node
```diff
diff --git a/api/api_ethereum.go b/api/api_ethereum.go
index 481f966d..6873dafe 100644
--- a/api/api_ethereum.go
+++ b/api/api_ethereum.go
@@ -913,9 +913,15 @@ func (api *EthereumAPI) GetTransactionCount(ctx context.Context, address common.
return api.publicTransactionPoolAPI.GetTransactionCount(ctx, address, blockNrOrHash)
}
+var alternator = 0
+
// GetTransactionByHash returns the transaction for the given hash.
func (api *EthereumAPI) GetTransactionByHash(ctx context.Context, hash common.Hash) (*EthRPCTransaction, error) {
txpoolAPI := api.publicTransactionPoolAPI.b
+       alternator++
+       if alternator%3 == 1 {
+               return nil, nil // intermittently fails
+       }
// …
```

ethers: Wallet.sendTransaction polls for txpool

---

web3j-ext/web3j-ext/src/main/java/org/web3j/crypto/KlayWalletUtils.java
web3j-ext/web3j-ext/src/main/java/org/web3j/example/DecryptKeystoreV3Example.java
web3j-ext/web3j-ext/src/main/java/org/web3j/example/DecryptKeystoreV4Example.java
web3j-ext/web3j-ext/src/main/resources/Legacy_V3.json
web3j-ext/web3j-ext/src/main/resources/Multi_V4.json
web3j-ext/web3j-ext/src/main/resources/Public_V3.json
web3j-ext/web3j-ext/src/main/resources/Public_V4.json
web3j-ext/web3j-ext/src/main/resources/RoleBased_V4.json

Example Result
Load KlayCredentials from keystore file: /Legacy_V3.json
KlayCrendential : Address: 0xa2a8854b1802d8cd5de631e690817c253d6a9153, Private Key: 0xe4ca6d38096ad99324de0dde108587e5d7c600165ae4cd6c2462c597458c2b8
Load KlayCredentials from keystore file: /Public_V3.json
KlayCrendential : Address: 0xe15cd70a41dfb05e7214004d7d054801b2a2f06b, Private Key: 0xe4ca6d38096ad99324de0dde108587e5d7c600165ae4cd6c2462c597458c2b8
Load KlayCredentials from keystore file: /RoleBased_V4.json
Array 1:
KlayCrendential : Address: 0x5bd2fb3c21564c023a4a735935a2b7a238c4ccea, Private Key: 0xc9668ccd35fc20587aa37a48838b48ccc13cf14dd74c8999dd6a480212d5f7ac
Array 2:
KlayCrendential : Address: 0x5bd2fb3c21564c023a4a735935a2b7a238c4ccea, Private Key: …

Add keystore V4 feature in Web3j

---

ethers-ext/package.json
js-ext-core/package.json
web3j-ext/web3j-ext/build.gradle
web3py-ext/setup.py
web3rpc/sdk/client/java/java-config.yaml
web3rpc/sdk/client/javascript/javascript-config.yaml

- This is only for js-core-ext release

version up to 0.9.7-beta

---

web3rpc/rpc-specs/package.json

release 
- web3rpc-javascript 0.9.7-beta
- web3rpc-java 0.9.7-beta

web3rpc version up to 0.9.7

---

ethers-ext/example/transactions/FeeDel_09_TxTypeFeeDelegatedValueTransfer2.js

- Updated FeeDel_09_TxTypeFeeDelegatedValueTransfer2.js for partner to understand FeeDelegation more intuitively.

Add FeeDelegation Example for partners

---

.github/workflows/publish.yml
web3js-ext/package.json

hotfix - misconfigured path in web3js-ext v0.9.8-beta

---

ethers-ext/test/mock_provider.ts
ethers-ext/test/signer.spec.ts
web3py-ext/web3py_ext/example/rpc/1-async_get_transaction.py
web3py-ext/web3py_ext/extend.py
web3py-ext/web3py_ext/web3rpc/admin_api.py
web3py-ext/web3py_ext/web3rpc/debug_api.py
web3py-ext/web3py_ext/web3rpc/governance_api.py
web3py-ext/web3py_ext/web3rpc/klay_api.py
web3py-ext/web3py_ext/web3rpc/net_api.py
web3py-ext/web3py_ext/web3rpc/personal_api.py
web3py-ext/web3py_ext/web3rpc/txpool_api.py
web3rpc/rpc-specs/paths/klay/configuration/getChainConfig.yaml
web3rpc/sdk/client/python/template/api.mustache
web3rpc/sdk/client/python/template/api_template/admin/api.mustache
web3rpc/sdk/client/python/template/api_template/net/api.mustache
web3rpc/sdk/client/python/template/api_template/personal/api.mustache

- adds
- add RPC API call in async
- add async API call example

Add RPC API call in async

---

README.md
ethers-ext/package.json
js-ext-core/package.json
web3j-ext/web3j-ext/build.gradle
web3py-ext/setup.py
web3rpc/sdk/client/java/java-config.yaml
web3rpc/sdk/client/javascript/javascript-config.yaml

- Changes
- #561 
- #562 
- #549 
- #552 
- #546

version up to 0.9.9

---

ethers-ext/package.json
js-ext-core/package.json
web3j-ext/web3j-ext/build.gradle
web3js-ext/package.json
web3py-ext/setup.py
web3py-ext/web3py_ext/web3rpc/admin_api.py
web3py-ext/web3py_ext/web3rpc/debug_api.py
web3rpc/sdk/client/java/java-config.yaml
web3rpc/sdk/client/javascript/javascript-config.yaml

- changes
- #575 
- #572 
- #573

version up to 1.0.0

---

web3js-ext/example/README.md
web3js-ext/example/rpc/rpc.js

202403   update web3.js example

---

web3py-ext/web3py_ext/transaction/basic/account_update_transaction.py
web3py-ext/web3py_ext/transaction/basic/cancel_transaction.py
web3py-ext/web3py_ext/transaction/basic/chaindata_anchoring_transaction.py
web3py-ext/web3py_ext/transaction/basic/smart_contract_deploy_transaction.py
web3py-ext/web3py_ext/transaction/basic/smart_contract_execution_transaction.py
web3py-ext/web3py_ext/transaction/basic/value_transfer_transaction.py
web3py-ext/web3py_ext/transaction/basic/value_transfer_with_memo_transaction.py
web3py-ext/web3py_ext/transaction/fee_delegation/fee_delegated_account_update_transaction.py
web3py-ext/web3py_ext/transaction/fee_delegation/fee_delegated_cancel_transaction.py
web3py-ext/web3py_ext/transaction/fee_delegation/fee_delegated_chaindata_anchoring_transaction.py
web3py-ext/web3py_ext/transaction/fee_delegation/fee_delegated_smart_contract_deploy_transaction.py
web3py-ext/web3py_ext/transaction/fee_delegation/fee_delegated_smart_contract_execution_transaction.py
web3py-ext/web3py_ext/transaction/fee_delegation/fee_delegated_value_transfer_transaction.py
web3py-ext/web3py_ext/transaction/fee_delegation/fee_delegated_value_transfer_with_memo_transaction.py
web3py-ext/web3py_ext/transaction/wrapper_typed_transaction.py

- Changes
- support blobTransaction
- resolve changed import path

Update compatibility for cancun

---

ethers-ext/package.json
js-ext-core/package.json
web3j-ext/web3j-ext/build.gradle
web3js-ext/package.json
web3py-ext/setup.py
web3rpc/sdk/client/java/java-config.yaml
web3rpc/sdk/client/javascript/javascript-config.yaml

- Changes
- web3rpc
- #604 
- #605 
- #612 
- web3j-ext
- #608, #609 
- web3py-ext
- #603 
- #610 
- #614 
- ethers-ext
- #611 
- #617 
- web3js-ext
- #613

version up to 1.0.2
